Activate the extension if the workspace contains a bblayers.conf
yoctoproject/vscode-bitbake pull request #158
Opened 2024-03-07 19:30 UTC by WilsonZiweiWang

Ticket: 14106

Before, the extension will be activated whenever a file with languageId bitbake is opened and focused. Now it activates when vscode finds a bblayers.conf in the workspace.

2024-03-07 20:00 UTC, idillon-sfl commented
Can't believe we haven't thought of that sooner. I let Enguerrand approve

2024-03-08 10:06 UTC, deribaucourt requested changes

2024-03-08 10:06 UTC, deribaucourt commented on client/package.json
> +  "activationEvents": [
Have you also found a way to disable activation when .conf and .inc files are open?

2024-03-08 12:11 UTC, WilsonZiweiWang commented on client/package.json
> +    "workspaceContains:**/bblayers.conf"
Done.

2024-03-08 12:47 UTC, deribaucourt approved these changes
FANTASTIC! such a simple change but this will remove so much annoyances for users!

2024-03-08 12:50 UTC, merged