Feat: follow link prefixed with file:// in the string content
yoctoproject/vscode-bitbake pull request #27
Opened 2023-12-06 23:46 UTC by WilsonZiweiWang

Use the `documentLinkProvider` to provide the correct links in the string content.

2023-12-06 23:49 UTC, WilsonZiweiWang commented
@deribaucourt 
The workflow to provide the document links should be fine in this PR. However, I was encountering some difficulties in finding the files. Had no luck in debugging it.

2023-12-07 10:20 UTC, deribaucourt requested changes
I pushed a new commit that fixes vscode.search

2023-12-07 16:52 UTC, WilsonZiweiWang commented on client/src/documentLinkProvider.ts
> +        const [file] = await vscode.workspace.findFiles(link.value, undefined, 1)
Your fix is very good.

2023-12-07 16:53 UTC, WilsonZiweiWang commented on server/src/tree-sitter/analyzer.ts
> +              if (i > 0) {
Done.

2023-12-08 09:00 UTC, deribaucourt commented on client/src/documentLinkProvider.ts
> +        const [file] = await vscode.workspace.findFiles(link.value, undefined, 1)
There still was a performance issue in your latest branch. I pushed a commit that greatly reduces the CPU consumption when opening recipes with many defined file:// links.

2023-12-08 11:23 UTC, deribaucourt approved these changes
LGTM, I pushed a commit for performance

2023-12-11 08:23 UTC, merged